### ISSUE TITLE
OSError: symbolic link privilege not held

### ISSUE THREAD

**Issue by lesterlitch** [v7labs/darwin-py#151]
When downloading datasets on windows machines, the user seems to need admin access to the environment in order to create symlinks. I don't think should really be necessary? 

If I comment out the lines 252-255 in darwin > dataset > remote_dataset.py the issue is resolved. 

Could you include an option to not use symlinks for windows users that don't have admin access to the os?

**Comment by lesterlitch** [comment]
*tumbleweeds*

**Comment by andreaazzini** [comment]
Hi @lesterlitch, very sorry for the delay in response here, we typically reply to requests through our main support channel in a matter of hours, but because Github is monitored less frequently, we missed this one.

There have been several updates to our SDK since you reached out, when you try this now, are you still experiencing the reported behaviour?

Some of the changes we introduced address Windows issues with symlinks. However, those changes do not retroactively work on the datasets you've already pulled from Darwin. I would suggest to backup your current darwin directory (typically `~/.darwin`), and pull your dataset from scratch.

If the issue persists, we will keep investigating.

**Comment by jerem-lab** [comment]
I just created an account today and I'm still experiencing this issues on a brand new dataset

**Comment by lesterlitch** [comment]
I have the latest release, still have this issue. Please can you address as this is pretty fundamental and I have to overwrite the library with every update.

**Comment by andreaazzini** [comment]
Hello @lesterlitch and @jerem-lab, we have released a [new version of Darwin-Py](https://pypi.org/project/darwin-py/0.6.8/) that avoids creating symlinks when pulling datasets on non UNIX-like OSs.

Please, don't hesitate to re-open this issue should your problem persist!

**Comment by lesterlitch** [comment]
Wohoo, thank you!
