### ISSUE TITLE
Validation issues with dataset splitting

### ISSUE THREAD

**Issue by ck37** [v7labs/darwin-py#309]
Hello,

I'm trying to follow the dataset splitting shown at https://docs.v7labs.com/docs/loading-a-dataset-in-python but running into errors.

First, it looks like the function is expecting a floating point number rather than integer:

```bash
darwin dataset split {dataset_id} --val-percentage 0 --test-percentage 20
> Error: Invalid test percentage (20.0). Must be >= 0 and < 100
```

So it would be good to update the validation error message to say that it must be between 0 and 1, and to update the documentation page to be consistent with that.

This error message is also misleading for the validation set:

```bash
darwin dataset split {dataset_id} --val-percentage 20 --test-percentage 20
> Error: Invalid validation percentage (20.0). Must be >= 0 and < 100
```

However, if I change 20 to 0.2 I get a different, unclear error message:

```bash
darwin dataset split {dataset_id} --val-percentage 0 --test-percentage .20
> Error: test_size=1.0 should be either positive and smaller than the number of 
samples 41 or a float in the (0, 1) range
```

If I change val-percentage to be 0.2 it does succeed though:

```bash
darwin dataset split {dataset_id} --val-percentage 0.2 --test-percentage .2
```

So it would be helpful to support a validation percentage of 0 or improve the checking to note that it can't be 0.

Thanks,
Chris

**Comment by Fl4m3Ph03n1x** [comment]
Hello @ck37  and thank you for reporting this. 
We have taken your feedback into consideration and merged a PR that should fix the issue. 

Please let us know if you experience further problems and feel free to contact us for help/reporting should you find any.

We dearly appreciate your feedback, it is because of people like you that we can improve our open source project and make it better for everyone.

Best Regards,
V7 Wind Team
