### ISSUE TITLE
CLI Image pulling - big issue on Ubuntu

### ISSUE THREAD

**Issue by lschaupp** [v7labs/darwin-py#600]
This package has signifcant issues on an Ubuntu system for pulling images
using CLI. I am getting network issues almost every couple of minutes with it.

On the same machine (dual boot), switching to Windows (same ethernet connection), same package version -> no issues.

So this is really somehow Ubuntu network related.

Has anyone else had issues with it?
Could it somehow my network settings?

Any ideas?

**Comment by owencjones** [comment]
Hi @ischaupp,

We'd be happy to help if you are experiencing an issue that is caused by code, but ATM, this has too many other possibilities.

Happy to offer some tips, if you can provide some background on your Ubuntu network setup, but I'm not an expert in networking by any means, and my distro is very different!

**Comment by lschaupp** [comment]
Dear @owencjones,

Thanks for getting back. Can you confirm that you have done intensive testing on your side on various Ubuntu distros 
and have not experienced any issue? If so, I will try to debug this and try to find the root cause of it.

Cheers
Lukas

**Comment by owencjones** [comment]
Hi Lukas,

I personally run the system on Arch, but our unit tests are run on python versions 3.8-3.11 on Ubuntu images and these don't recreate any networking problems - however they are unit tests.  We have an end to end automated testing initiative currently in progress, and these would ultimately cover the `pull` action, but this is underway, rather than already in place.

So atm, short of running this on my own Ubuntu VM, which didn't recreate any issues, I haven't been able to recreate this.

Owen
