### ISSUE TITLE
breaking changes introduced in patch semantic increment

### ISSUE THREAD

**Issue by filippocastelli** [v7labs/darwin-py#824]
Latest release `0.8.59`  introduced  breaking changes c128fa0d2effa0d8aaa1a94b74c165f1464ef62b  wrt `0.8.58` , namely the removal of the `complex_polygon` annotation type and the API changes to reflect that, as per PR  #788 

The introduction of substantial API changes in what should be a `patch` semantic increment results in significant inconsistencies downstream packages that assume API stability.

**Comment by JBWilkie** [comment]
Thanks for getting in touch @filippocastelli, and apologies for the delayed response!

This is a valid complaint and it should have resulted in a major version change. We apologise for this oversight.

Unfortunately, we don't have plans to re-introduce the concepts that were removed as part of that PR, since they have been deprecated from the Darwin platform. In the future, we will pay more attention to breaking API changes.
