### ISSUE TITLE
Cannot get remote dataset with uppercase name

### ISSUE THREAD

**Issue by Krystex** [v7labs/darwin-py#851]
Hi all!

Somehow, when I create a dataset with an uppercase word in it, I cannot get it with the `get_remote_dataset` function.

To reproduce:
```python
from darwin.client import Client
client = Client.local()
client.create_dataset("TEST_dataset")
client.get_remote_dataset("TEST_dataset")
```

The last line throws the following stacktrace:
```stacktrace
    213     return RemoteDatasetV2(
    214         name=dataset["name"],
    215         slug=dataset["slug"],
   (...)
    220         client=self,
    221     )
    222 if not matching_datasets:
--> 223     raise NotFound(str(parsed_dataset_identifier))
    224 if parsed_dataset_identifier.version:
    225     matching_datasets[0].release = parsed_dataset_identifier.version

NotFound: Not found: 'companyname/TEST_dataset'
```

It works if I try got get the dataset with the lowercase version (`client.get_remote_dataset("test_dataset")`)

**Comment by JBWilkie** [comment]
Hello @Krystex, thanks for raising this! The reason you're running into this issue is that `get_remote_dataset()` expects a `dataset_identifier` argument [of type `DatasetIdentifier`](https://github.com/v7labs/darwin-py/blob/f8296729e145d6c2b43f42d685af4f4d6f168f61/darwin/dataset/identifier.py#L5)

This is a string containing the substrings:
`<team-slug>/<dataset-slug>`

Therefore, dataset names passed to the function need to be [sluggified](https://docs.v7labs.com/reference/datasetidentifier), in your case it would be 'test_dataset'

There's an example of how to use `get_remote_dataset()` in [this](https://docs.v7labs.com/docs/create-a-dataset-2) article

**Comment by Krystex** [comment]
Thanks for the link! I'm trying it like in the article described, but it still doesn't work:
```python
from darwin.client import Client
client = Client.local()
client.create_dataset("TEST_dataset")
client.get_remote_dataset(f"{client.default_team}/TEST_dataset")
```

The same error as before is thrown

**Comment by JBWilkie** [comment]
Hi @Krystex! Apologies for not covering this explicitly previously, but [sluggifying](https://pypi.org/project/python-slugify/) a dataset name involves lowercasing it and replacing spaces with hyphens
<img width="781" alt="image" src="https://github.com/v7labs/darwin-py/assets/124276291/327d29fc-6109-42bb-8cc5-bdd1391543f1">


Therefore instead of `TEST_dataset`, you'll need to pass `test_dataset`

**Comment by Krystex** [comment]
Ahh, I didn't know sluggifying is a standard procedure, thanks for linking the library!
